daemonize: false
syslog: stdout

nfacctd_port: 2055
nfacctd_ip: 0.0.0.0

# IMPORTANT: v9 mode
nfacctd_netflow_version: 9

# keep templates alive
nfacctd_timeouts: tcp=60:udp=30

plugins: print

geoipv2_file: /etc/pmacct/GeoLite2-Country.mmdb 

aggregate: src_host,dst_host,src_port,dst_port,proto,src_host_country,dst_host_country

print_output: json
print_output_file: /data/pmacct.json

debug: true
