[[inputs.tail]]
  files = ["/data/pmacct.json"]
  from_beginning = false
  data_format = "json_v2"
  name_override = "pmacct"

  [[inputs.tail.json_v2]]
    measurement_name = "pmacct"

    [[inputs.tail.json_v2.tag]]
      path = "ip_src"

    [[inputs.tail.json_v2.tag]]
      path = "ip_dst"

    [[inputs.tail.json_v2.tag]]
      path = "ip_proto"

    [[inputs.tail.json_v2.tag]]
      path = "event_type"

    [[inputs.tail.json_v2.field]]
      path = "packets"
      type = "int"

    [[inputs.tail.json_v2.field]]
      path = "bytes"
      type = "int"

    [[inputs.tail.json_v2.tag]]
      path = "country_ip_src"
    
    [[inputs.tail.json_v2.tag]]
      path = "country_ip_dst"

# =========================
# OUTPUT: InfluxDB
# =========================

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "pmacct"
  retention_policy = "autogen"

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"

[agent]
  debug = true
